/**
 * Generates packages/tokens/tokens.css from src/index.ts.
 *   tsx scripts/build-css.ts          → write tokens.css
 *   tsx scripts/build-css.ts --check  → exit 1 if tokens.css is stale
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { alphaColors, colors, fonts, radii, type Palette, type ThemeName } from '../src/index';

const kebab = (s: string) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

const colorVars = (theme: ThemeName, indent: string) => {
  const palette: Palette = colors[theme];
  const lines = Object.entries(palette).map(([k, v]) => `${indent}--color-${kebab(k)}: ${v};`);
  for (const [k, v] of Object.entries(alphaColors[theme])) lines.push(`${indent}--color-${kebab(k)}: ${v};`);
  lines.push(`${indent}color-scheme: ${theme};`);
  return lines.join('\n');
};

const fallback = { serif: 'Georgia, serif', sans: 'system-ui, sans-serif', mono: 'ui-monospace, monospace' };
const fontVars = (Object.keys(fonts) as (keyof typeof fonts)[])
  .map((k) => `  --font-${k}: '${fonts[k]}', ${fallback[k]};`)
  .join('\n');
const radiusVars = Object.entries(radii)
  .map(([k, v]) => `  --radius-${kebab(k)}: ${v}px;`)
  .join('\n');

const css = `/* GENERATED by packages/tokens/scripts/build-css.ts — do not edit by hand. */

:root {
${fontVars}
${radiusVars}
}

/* Light by default */
:root {
${colorVars('light', '  ')}
}

/* Dark when the OS prefers it, unless explicitly forced light */
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${colorVars('dark', '    ')}
  }
}

/* Explicit overrides on <html data-theme="…"> */
:root[data-theme="dark"],
[data-theme="dark"] {
${colorVars('dark', '  ')}
}

:root[data-theme="light"],
[data-theme="light"] {
${colorVars('light', '  ')}
}
`;

const out = resolve(dirname(fileURLToPath(import.meta.url)), '../tokens.css');
if (process.argv.includes('--check')) {
  const current = existsSync(out) ? readFileSync(out, 'utf8') : '';
  if (current !== css) {
    console.error('tokens.css is out of date — run `pnpm --filter @morrow/tokens build:css`');
    process.exit(1);
  }
  console.log('tokens.css is up to date');
} else {
  writeFileSync(out, css);
  console.log(`wrote ${out}`);
}
