import type { Metadata } from 'next';
import Link from 'next/link';
import { LegalPage, Section } from '@/components/legal/LegalPage';
import { LEGAL } from '@/lib/legal';

export const metadata: Metadata = { title: 'Terms of Service' };

/** Public terms of service (linked from Sign in). */
export default function TermsPage() {
  const mail = <a href={`mailto:${LEGAL.contactEmail}`}>{LEGAL.contactEmail}</a>;
  return (
    <LegalPage
      title="Terms of Service"
      intro={
        <p>
          These terms govern your use of Morrow, a service operated by {LEGAL.operator} (&ldquo;we&rdquo;). By signing
          in you agree to them. If you don&apos;t agree, please don&apos;t use Morrow.
        </p>
      }
    >
      <Section title="What Morrow is">
        <p>
          Morrow gives you one reading a day, written by AI from the accounts you choose to connect, and makes
          prophecies that it checks against those accounts later. It is made for reflection and entertainment.
        </p>
        <p>
          <strong>Morrow is not advice.</strong> Readings and prophecies are generated by AI, can be wrong, and are not
          medical, legal, financial, psychological or any other professional advice. Don&apos;t rely on them for
          decisions that matter; make those yourself, with people you trust.
        </p>
      </Section>

      <Section title="Your account">
        <ul>
          <li>You must be at least 16 years old to use Morrow.</li>
          <li>You sign in with your own Google account and are responsible for what happens under it.</li>
          <li>Only connect accounts that belong to you.</li>
        </ul>
      </Section>

      <Section title="Your data">
        <p>
          You keep ownership of your data. You give us permission to process it only to provide Morrow to you, as
          described in our <Link href="/privacy">Privacy Policy</Link>. You can disconnect sources or forget everything
          at any time.
        </p>
      </Section>

      <Section title="Fair use">
        <p>You agree not to:</p>
        <ul>
          <li>misuse Morrow, interfere with it, or try to access it in ways we don&apos;t provide;</li>
          <li>try to make Morrow produce harmful, unlawful or harassing content;</li>
          <li>use Morrow to track, profile or read about another person;</li>
          <li>resell, copy or scrape the service.</li>
        </ul>
        <p>There are daily limits on questions. We may suspend accounts that break these terms.</p>
      </Section>

      <Section title="Third-party services">
        <p>
          Morrow connects to services such as Google and Spotify under their own terms. We&apos;re not responsible for
          them, and your use of them remains subject to their terms and policies.
        </p>
      </Section>

      <Section title="Changes and availability">
        <p>
          Morrow is in active development. Features may change, be limited or stop, and the service may be unavailable
          at times. We may update these terms; if a change is significant we&apos;ll tell you in the app, and continuing
          to use Morrow means you accept the new terms.
        </p>
      </Section>

      <Section title="Ending your use">
        <p>
          You can stop using Morrow at any time and use Forget everything to delete your account and all your data. We may end or suspend
          access if you break these terms or if we shut the service down, and we&apos;ll give notice where we can.
        </p>
      </Section>

      <Section title="Disclaimers and liability">
        <p>
          Morrow is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo;, without warranties of any kind. To the
          fullest extent the law allows, we aren&apos;t liable for indirect, incidental or consequential losses, or for
          decisions you make based on a reading. Nothing in these terms limits rights you have that can&apos;t be
          limited by law.
        </p>
      </Section>

      <Section title="Governing law">
        <p>These terms are governed by the laws of {LEGAL.jurisdiction}.</p>
      </Section>

      <Section title="Contact">
        <p>Questions about these terms: {mail}.</p>
      </Section>
    </LegalPage>
  );
}
