import type { Metadata } from 'next';
import Link from 'next/link';
import { LegalPage, Section } from '@/components/legal/LegalPage';
import { LEGAL } from '@/lib/legal';

export const metadata: Metadata = { title: 'Privacy Policy' };

/** Public privacy policy (linked from Sign in; required for Google and Spotify app review). */
export default function PrivacyPage() {
  const mail = <a href={`mailto:${LEGAL.contactEmail}`}>{LEGAL.contactEmail}</a>;
  return (
    <LegalPage
      title="Privacy Policy"
      intro={
        <p>
          Morrow reads the accounts you choose to connect and turns them into one reading a day. This policy explains
          exactly what it reads, what it keeps, how long, and how to make it forget. Morrow is operated by{' '}
          {LEGAL.operator} (&ldquo;we&rdquo;).
        </p>
      }
    >
      <Section title="The short version">
        <ul>
          <li>You choose each source. Nothing is read until you connect it, and you can disconnect it at any time.</li>
          <li>Raw data from your sources is deleted within 24 hours. Morrow keeps only a distilled summary.</li>
          <li>Morrow never reads or predicts about health, pregnancy, death, money trouble or relationship breakdown.</li>
          <li>We don&apos;t sell your data, show you ads, or use your data to train AI models.</li>
          <li>You can see everything Morrow knows about you, forget any single fact, or forget everything.</li>
        </ul>
      </Section>

      <Section title="What we collect">
        <p>
          <strong>Your account.</strong> When you sign in with Google we receive your name, email address and profile
          picture. We also store your time zone so your reading starts at the right hour.
        </p>
        <p>
          <strong>Google Calendar</strong> (read only, if you connect it). From the calendars in your account we read
          events from the last 90 days and the next 30: start and end times, title, a short plain-text excerpt of the
          description, location, organizer, attendees and their responses, and the calendar&apos;s name. We never read
          attachments or video-call details, and we don&apos;t keep titles or details of events you&apos;re not part of.
        </p>
        <p>
          <strong>Spotify</strong> (if you connect it). Your recently played tracks and your top artists and tracks.
        </p>
        <p>
          <strong>Gmail</strong> (read only, if you connect it). Messages from the last few weeks, excluding spam, trash,
          chats, promotions, social and forum mail: sender and recipients, subject, date, labels and the plain text of
          the message without quoted replies. We never read attachments.
        </p>
        <p>
          <strong>What you tell Morrow.</strong> The questions you ask in your daily reading and Morrow&apos;s answers.
        </p>
        <p>
          <strong>Technical data.</strong> A session cookie to keep you signed in and a short-lived cookie that records
          your time zone at sign-in. Our hosting provider keeps standard server logs. We don&apos;t use advertising or
          analytics trackers.
        </p>
      </Section>

      <Section title="How we use it">
        <p>We use your data only to provide Morrow to you:</p>
        <ul>
          <li>to build your dossier — a short set of patterns about your days, such as rhythms, pursuits and the people you meet;</li>
          <li>to write your daily reading and answer your questions;</li>
          <li>to check whether a prophecy has come true, by watching the sources it depends on;</li>
          <li>to keep the service secure and working.</li>
        </ul>
        <p>
          Morrow&apos;s readings are generated by AI. Parts of your dossier, your questions and, for Gmail, short excerpts
          of recent threads are sent to our AI provider to produce each reading. Sensitive topics are filtered out
          before anything is sent.
        </p>
      </Section>

      <Section title="Google user data">
        <p>
          Morrow&apos;s use and transfer to any other app of information received from Google APIs will adhere to the{' '}
          <a href="https://developers.google.com/terms/api-services-user-data-policy" target="_blank" rel="noreferrer">
            Google API Services User Data Policy
          </a>
          , including the Limited Use requirements.
        </p>
        <ul>
          <li>We use Google data only to provide and improve the features you see in Morrow.</li>
          <li>We don&apos;t transfer it to others except to run the service (the processors listed below), to comply with the law, or with your permission.</li>
          <li>We don&apos;t use it for advertising, sell it, or use it to train general AI models.</li>
          <li>No person reads it unless you ask us to, it&apos;s needed for security, or the law requires it.</li>
        </ul>
      </Section>

      <Section title="How long we keep it">
        <ul>
          <li><strong>Raw source data</strong> (events, plays, messages as fetched): deleted within 24 hours.</li>
          <li><strong>Your dossier and the summaries built from your sources</strong>: kept while the source stays connected, rebuilt as new data arrives. Mail summaries (who, when, a one-line note per thread — never message bodies) are kept for up to 180 days.</li>
          <li><strong>Readings, your questions and prophecies</strong>: kept until you delete them, so Morrow can remember past readings.</li>
          <li><strong>Your account</strong> (name, email, time zone): kept until you choose Forget everything, which deletes it along with everything else.</li>
        </ul>
      </Section>

      <Section title="Who processes it">
        <p>We use a small number of providers to run Morrow. They process data on our behalf and only as needed:</p>
        <ul>
          <li><strong>Vercel</strong> — hosting, and access to AI models through Vercel AI Gateway.</li>
          <li><strong>Anthropic</strong> — the Claude models that write readings and answers.</li>
          <li><strong>Neon</strong> — our database.</li>
          <li><strong>Google and Spotify</strong> — the sources you connect, under their own privacy policies.</li>
        </ul>
        <p>Your data may be processed in the United States and other countries where these providers operate.</p>
      </Section>

      <Section title="Security">
        <p>
          Data is encrypted in transit. The tokens that let Morrow read your connected accounts are encrypted at rest,
          and access is read only. No system is perfectly secure; if something goes wrong that affects your data, we
          will tell you.
        </p>
      </Section>

      <Section title="Your choices">
        <ul>
          <li><strong>See what Morrow knows:</strong> Sources → View dossier.</li>
          <li><strong>Forget one fact:</strong> in your dossier, choose Forget this.</li>
          <li><strong>Disconnect a source:</strong> Sources. This deletes that source&apos;s raw data and rebuilds your dossier without it.</li>
          <li><strong>Forget everything:</strong> Sources → Forget everything permanently deletes your account — your dossier, readings, questions, prophecies and all source data — disconnects every source, revokes Morrow&apos;s Google access and signs you out. It can&apos;t be undone.</li>
          <li>You can also remove Morrow&apos;s access at any time from your <a href="https://myaccount.google.com/permissions" target="_blank" rel="noreferrer">Google account</a> or <a href="https://www.spotify.com/account/apps/" target="_blank" rel="noreferrer">Spotify account</a>.</li>
        </ul>
        <p>
          Depending on where you live you may have further rights, such as to access, correct, export or delete your
          data, or to object to how it&apos;s used. Write to {mail} and we&apos;ll respond within 30 days.
        </p>
      </Section>

      <Section title="Children">
        <p>Morrow is not for anyone under 16, and we don&apos;t knowingly collect data from children.</p>
      </Section>

      <Section title="Changes">
        <p>
          If we change this policy we&apos;ll update the date above, and tell you in the app before any change that
          affects how your data is used.
        </p>
      </Section>

      <Section title="Contact">
        <p>
          Questions or requests: {mail}. See also our <Link href="/terms">Terms of Service</Link>.
        </p>
      </Section>
    </LegalPage>
  );
}
